#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: C##CRUD
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
